#!/bin/bash
# Quick setup for ClinicFlow storage bucket

echo "🔧 ClinicFlow Storage Setup"
echo "============================="
echo ""
echo "To fix the 'Bucket not found' error, you need to create the medical-media storage bucket."
echo ""
echo "Follow these steps:"
echo ""
echo "1. Go to your Supabase Dashboard: https://app.supabase.com"
echo "2. Select your ClinicFlow project"
echo "3. Click 'Storage' in the left sidebar"
echo "4. Click 'Create a new bucket' button"
echo "5. Enter these details:"
echo "   - Bucket name: medical-media"
echo "   - Check 'Public bucket' ✓"
echo "   - File size limit: 104857600 (100MB)"
echo "   - Allowed MIME types: image/*, video/*"
echo ""
echo "6. Click 'Create bucket'"
echo ""
echo "7. Refresh your ClinicFlow app and try uploading media again"
echo ""
echo "✅ Once created, the media upload feature will work!"
